config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]

  # GET /blog_posts or /blog_posts.json
  def index
    @blog_posts = blog_posts
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was successfully created." }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Blog post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :body)
    end

    def search_query 
      params[:query]
    end

    def blog_posts 
     query = BlogPost.ransack(title_or_body_cont_any: search_query)
     query = query.result(:distinct=>true)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_blog_post.html.erb
<div id="<%= dom_id blog_post %>">
  <p>
    <strong>Title:</strong>
    
    <%= blog_post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog_post.body %>
  </p>

</div>

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post) do |form| %>
  <% if blog_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Show ", @blog_post %> |
  <%= link_to "Back ", blog_posts_path, class: "btn btn-outline-secondary" %>
</div>

app/views/blog_posts/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Blog posts</h1>

<%= form_with url: blog_posts_path, method: :get do |form| %>
   <%= form.text_field :query %>
    <%= form.submit "Search" %>
<% end %>

<div id="blog_posts">
  <% @blog_posts.each do |blog_post| %>
    <%= render blog_post %>
    <p>
      <%= link_to "Show ", blog_post, class:"btn btn-outline-primary" %>
    </p>
  <% end %>
</div>

<%= link_to "New blog post", new_blog_post_path, class: "btn btn-outline-primary" %>

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

app/views/blog_posts/new.html.erb
<h1>New blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Back ", blog_posts_path, class:"btn btn-outline-secondary" %>
</div>

app/views/blog_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog_post %>

<div>
  <%= link_to "Edit ", edit_blog_post_path(@blog_post) %> |
  <%= link_to "Back ", blog_posts_path, class:"btn btn-outline-secondary" %>

  <%= button_to "Destroy ", @blog_post, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchSustem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="application.css">
  </head>
  <style>
  
  </style>

  <body>
    <%= yield %>
  </body>

</html>